targets:

  # needs patched u-boot for emmc r/w https://lists.denx.de/pipermail/u-boot/2021-February/441964.html
  turris-omnia-emmc:
    resources:
      RawSerialPort:
        port: "/dev/turris-omnia"
      ModbusTCPCoil:
        host: quido.testbed-01.vpn.true.cz
        coil: 0
        managed_coils: 8
        exclusive_coil_mode: True
        write_multiple_coils: True
    drivers:
      ModbusCoilDriver: {}
      DigitalOutputPowerDriver: {}
      SerialDriver:
        txdelay: 0.01
      ShellDriver:
        console_ready: Please press Enter to activate this console.
        prompt: 'root@[\w()]+:[^ ]+ '
        login_prompt: built-in shell (ash)
        await_login_timeout: 15
        username: kingbanik
      UBootDriver:
        prompt: '=> '
        init_commands:
          - setenv bootargs earlyprintk console=ttyS0,115200
          - setenv set_blkcnt 'setexpr blkcnt ${filesize} + 0x7ffff && setexpr blkcnt ${blkcnt} / 0x80000 && setexpr blkcnt ${blkcnt} * 0x400'
          - dhcp ${kernel_addr_r} prplos-mvebu-cortexa9-cznic_turris-omnia-sysupgrade.img
        boot_command: run set_blkcnt && mmc dev 0 0 && mmc erase 0 ${blkcnt} && mmc write ${kernel_addr_r} 0 ${blkcnt} && run bootcmd
      UBootStrategy: {}

  turris-omnia-initramfs:
    resources:
      RawSerialPort:
        port: "/dev/turris-omnia"
      ModbusTCPCoil:
        host: quido.testbed-01.vpn.true.cz
        coil: 0
        managed_coils: 8
        exclusive_coil_mode: True
        write_multiple_coils: True
    drivers:
      ModbusCoilDriver: {}
      DigitalOutputPowerDriver: {}
      SerialDriver:
        txdelay: 0.01
      ShellDriver:
        console_ready: Please press Enter to activate this console.
        prompt: 'root@[\w()]+:[^ ]+ '
        login_prompt: built-in shell (ash)
        await_login_timeout: 15
        username: kingbanik
      UBootDriver:
        prompt: '=> '
        init_commands:
          - setenv kernel_addr_r 0x2000000
          - setenv bootargs earlyprintk console=ttyS0,115200
          - dhcp 0x2000000 prplos-mvebu-cortexa9-cznic_turris-omnia-initramfs-kernel.bin
        boot_command: bootm 0x2000000
      UBootStrategy: {}

  wnc-freedom-emmc:
    resources:
      RawSerialPort:
        port: "/dev/wnc-freedom"
      ModbusTCPCoil:
        host: quido.testbed-01.vpn.true.cz
        coil: 2
        managed_coils: 8
        exclusive_coil_mode: True
        write_multiple_coils: True
    drivers:
      ModbusCoilDriver: {}
      DigitalOutputPowerDriver: {}
      SerialDriver: {}
      ShellDriver:
        console_ready: Please press Enter to activate this console.
        prompt: 'root@[\w()]+:[^ ]+ '
        login_prompt: built-in shell (ash)
        login_timeout: 120
        await_login_timeout: 16
        username: kingbanik
      UBootDriver:
        prompt: 'IPQ9574# '
        init_command_timeout: 75
        init_commands:
          - setenv serverip 10.0.0.1
          - setenv ipaddr 10.0.0.2
          - setenv loadaddr 0x50000000
          - sleep 5
          - tftpboot ${loadaddr} prplos-ipq95xx-generic-prpl_freedom-update_script.itb
          - source ${loadaddr}:update-script
          - setenv tftppath
          - setenv img_kernel prplos-ipq95xx-generic-prpl_freedom-kernel.itb
          - setenv img_rootfs prplos-ipq95xx-generic-prpl_freedom-rootfs.itb
          - setenv img_uboot
          - setenv img_xbl
          - setenv img_smd
          - setenv update_rescue_bank yes
          - mmc dev 0
          - mmc erase 0x534022 0x40000
          - run update_prpl
        boot_command: run bootcmd
      UBootStrategy: {}

  mxl25641-hdk-6-emmc:
    resources:
      RawSerialPort:
        port: "/dev/mxl25641-hdk-6"
      ModbusTCPCoil:
        host: quido.testbed-01.vpn.true.cz
        coil: 1
        managed_coils: 8
        exclusive_coil_mode: True
        write_multiple_coils: True
    drivers:
      ModbusCoilDriver: {}
      DigitalOutputPowerDriver: {}
      SerialDriver:
        txdelay: 0.01
      ShellDriver:
        console_ready: Please press Enter to activate this console.
        prompt: 'root@[\w()]+:[^ ]+ '
        login_prompt: built-in shell (ash)
        username: kingbanik
      UBootDriver:
        prompt: 'Lightning #'
        console_decodeerrors: 'backslashreplace'
        init_command_timeout: 60
        init_commands:
          - setenv serverip 192.168.1.2
          - setenv ipaddr 192.168.1.1
          - setenv loadaddr 0x8200000
          - tftpboot ${loadaddr} prplos-intel_x86-lgm-PRPL_OSP_v2-update_script.itb
          - source ${loadaddr}:update-script
          - setenv tftppath
          - setenv img_kernel prplos-intel_x86-lgm-PRPL_OSP_v2-wgrtd159be_b_wav700-ext4.img
          - setenv img_uboot
          - setenv img_rbe
          - setenv img_smd
          - setenv update_rescue_bank yes
          - mmc dev 0
          - mmc erase 0x86c00 0x10000
          - run update_prpl
        boot_command: run bootcmd
      UBootStrategy: {}
