---
description: Add compiler security features

additional_packages:
  - feed: feed_prplos
    packages:
      - apparmor-prpl
      - apparmor-utils-prpl
      - apparmor-profiles-prpl
      - libapparmor-prpl

  - feed: packages
    packages:
      - audit
      - auditd
      - libev
      - libaudit
      - libauparse

diffconfig: |
          CONFIG_DEVEL=y
          CONFIG_JSON_CHECKSEC_MITIGATIONS_REPORT=y
          CONFIG_BUSYBOX_DEFAULT_PIE=y
          CONFIG_GCC_DEFAULT_PIE=y
          CONFIG_KERNEL_CC_STACKPROTECTOR_STRONG=y
          CONFIG_PKG_ASLR_PIE_ALL=y
          CONFIG_PKG_CC_STACKPROTECTOR_STRONG=y
          CONFIG_PKG_FORTIFY_SOURCE_2=y
          CONFIG_TOOLCHAINOPTS=y
          CONFIG_KERNEL_SECURITY=y
          CONFIG_KERNEL_SECURITYFS=y
          CONFIG_KERNEL_SECURITY_NETWORK=y
          CONFIG_KERNEL_SECURITY_PATH=y
          CONFIG_KERNEL_SECURITY_APPARMOR=y
          CONFIG_KERNEL_SECURITY_APPARMOR_HASH=y
          CONFIG_KERNEL_SECURITY_APPARMOR_HASH_DEFAULT=y
          CONFIG_KERNEL_DEFAULT_SECURITY_APPARMOR=y
          CONFIG_KERNEL_LSM="lockdown,yama,loadpin,safesetid,integrity,apparmor"
          CONFIG_KERNEL_AUDIT=y
          CONFIG_KERNEL_AUDITSYSCALL=y
          CONFIG_KERNEL_AUDIT_GENERIC=y
          CONFIG_KERNEL_AUDIT_COMPAT_GENERIC=y
