Create R alias:

  $ alias R="${CRAM_REMOTE_COMMAND:-}"

Check that ubus has expected datamodels available:

  $ R "ubus list | grep '[[:upper:]]' | grep -v -e '\.[[:digit:]]' -e '^Cellular' -e 'Device.Cellular' -e 'WiFi.Vendor.Daemon' -e 'WiFi.Vendor.ModuleMode' -e '^WiFi.Vendor.MLO' -e '^Bridging.Bridge.[SV]' -e 'WiFi.Vendor.ReconfManager'"
  ACLManager
  ACLManager.Role
  Bridging
  Bridging.Bridge
  BulkData
  BulkData.Profile
  Buttons
  Buttons.Action
  Buttons.Button
  CPUs
  CPUs.CPU
  CaptivePortal
  CaptivePortal.LANInterface
  ConMon
  ConMon.Entry
  ConnectionTrackingQuery
  ConnectionTrackingQuery.NotifyFlow
  Cthulhu
  Cthulhu.Config
  Cthulhu.Config.Debug
  Cthulhu.Config.LocalPolicyManager
  Cthulhu.Config.Syslog
  Cthulhu.Container
  Cthulhu.Container.Instances
  Cthulhu.Information
  Cthulhu.Information.LocalPolicyManager
  Cthulhu.Information.LocalPolicyManager.Action
  Cthulhu.LocalManagement
  Cthulhu.LocalManagement.Action
  Cthulhu.Plugins
  Cthulhu.PluginsPrivate
  Cthulhu.PluginsPrivate.NetworkConfig
  Cthulhu.PluginsPrivate.NetworkConfig.FirewallRules
  Cthulhu.PluginsPrivate.NetworkConfig.Interfaces
  Cthulhu.Sandbox
  Cthulhu.Sandbox.Instances
  Cthulhu.Sandbox.Instances.Plugins.DHCP
  Cthulhu.Sandbox.Instances.Plugins.DHCP.Interfaces
  DHCPv4Client
  DHCPv4Client.Client
  DHCPv4Server
  DHCPv4Server.Pool
  DHCPv6Client
  DHCPv6Client.Client
  DHCPv6Server
  DHCPv6Server.Pool
  DNS
  DNS.Client
  DNS.Client.Server
  DNS.Diagnostics
  DNS.Diagnostics.NSLookupDiagnostics
  DNS.Diagnostics.NSLookupDiagnostics.Result
  DNS.Relay
  DNS.Relay.Config
  DNS.Relay.Config.Unbound
  DNS.Relay.Forwarding
  DNS.X_PRPLWARE-COM_ForwardZone
  DNS.X_PRPLWARE-COM_Host
  DNS.X_PRPLWARE-COM_RebindProtection
  DNS.X_PRPLWARE-COM_RebindProtection.DomainExceptions
  DNS.X_PRPLWARE-COM_RebindProtection.IPExceptions
  DNS.Zone
  DNSSD
  DNSSD.Advertise
  DNSSD.Service
  DSLite
  DSLite.InterfaceSetting
  Device
  Device.Bridging
  Device.BulkData
  Device.CaptivePortal
  Device.DHCPv4
  Device.DHCPv4.Server
  Device.DHCPv6
  Device.DHCPv6.Server
  Device.DNS
  Device.DNS.SD
  Device.DSLite
  Device.DeviceInfo
  Device.DeviceInfo.KernelFaults
  Device.DeviceInfo.PowerStatus
  Device.DeviceInfo.ProcessFaults
  Device.DeviceInfo.Reboots
  Device.DeviceInfo.TemperatureStatus
  Device.DynamicDNS
  Device.Ethernet
  Device.Firewall
  Device.Hardware
  Device.Hardware.CPUs
  Device.Hardware.X_PRPLWARE-COM_FlashDevice
  Device.HomePlug
  Device.Hosts
  Device.IP
  Device.IP.Diagnostics
  Device.InterfaceStack
  Device.LEDs
  Device.Logical
  Device.MQTT
  Device.MQTT.Broker
  Device.ManagementServer
  Device.NAT
  Device.NeighborDiscovery
  Device.Optical
  Device.PCP
  Device.PPP
  Device.PacketInterception
  Device.PeriodicFileTransfer
  Device.QoS
  Device.RouterAdvertisement
  Device.Routing
  Device.SFPs
  Device.SSH
  Device.Schedules
  Device.Security
  Device.SoftwareModules
  Device.Syslog
  Device.Time
  Device.UPnP
  Device.UPnP.Description
  Device.UPnP.Discovery
  Device.USB
  Device.UserInterface
  Device.Users
  Device.WiFi
  Device.XPON
  Device.X_PRPLWARE-COM_Buttons
  Device.X_PRPLWARE-COM_ConMon
  Device.X_PRPLWARE-COM_ConnectionTrackingQuery
  Device.X_PRPLWARE-COM_GenericNetworkInterface
  Device.X_PRPLWARE-COM_MCASTD
  Device.X_PRPLWARE-COM_MultiSettings
  Device.X_PRPLWARE-COM_PersistentConfiguration
  Device.X_PRPLWARE-COM_SoftwareModules
  Device.X_PRPLWARE-COM_WANManager
  Device.X_PRPLWARE-COM_WiFiScheduler
  DeviceInfo
  DeviceInfo.DeviceImageFile
  DeviceInfo.FirmwareImage
  DeviceInfo.Location
  DeviceInfo.LogRotate
  DeviceInfo.MemoryStatus
  DeviceInfo.MemoryStatus.MemoryMonitor
  DeviceInfo.ProcessStatus
  DeviceInfo.ProcessStatus.CPU
  DeviceInfo.ProcessStatus.Process
  DeviceInfo.Processor
  DeviceInfo.VendorConfigFile
  DeviceInfo.VendorLogFile
  Devices
  Devices.Config
  Devices.Config.global
  Devices.Config.location
  Devices.Config.mDNSScanner
  Devices.Config.mod-self
  Devices.Config.priority
  Devices.Device
  Devices.Query
  DynamicDNS
  DynamicDNS.Client
  DynamicDNS.Server
  Ethernet
  Ethernet.Interface
  Ethernet.Link
  Ethernet.RMONStats
  Ethernet.VLANTermination
  Ethernet.WoL
  Firewall
  Firewall.Chain
  Firewall.ConnectionTracking
  Firewall.ConnectionTracking.SIP
  Firewall.DMZ
  Firewall.InterfaceSetting
  Firewall.Level
  Firewall.Log
  Firewall.Pinhole
  Firewall.Policy
  Firewall.Service
  Firewall.Set
  Firewall.X_PRPLWARE-COM_InterfaceSetting
  Firewall.X_PRPLWARE-COM_WANAccess
  Firewall.X_PRPLWARE-COM_WANAccess.BlockList
  GenericNetworkInterface
  GenericNetworkInterface.Interface
  Hardware
  Hardware.FlashDevice
  HomePlug
  HomePlug.Interface
  Hosts
  Hosts.AccessControl
  Hosts.Host
  Hosts.X_PRPLWARE-COM_HostConfig
  IP
  IP.ActivePort
  IP.Interface
  IPDiagnostics
  IPDiagnostics.DownloadDiagnostics
  IPDiagnostics.DownloadDiagnostics.IncrementalResult
  IPDiagnostics.DownloadDiagnostics.PerConnectionResult
  IPDiagnostics.IPLayerCapacityMetrics
  IPDiagnostics.IPLayerCapacityMetrics.IPLayerCapacityAuthCode
  IPDiagnostics.IPLayerCapacityMetrics.IncrementalResult
  IPDiagnostics.IPLayerCapacityMetrics.ModalResult
  IPDiagnostics.IPLayerCapacityMetrics.Process
  IPDiagnostics.IPPing
  IPDiagnostics.IPPing.Process
  IPDiagnostics.TraceRoute
  IPDiagnostics.TraceRoute.Process
  IPDiagnostics.TraceRoute.RouteHops
  IPDiagnostics.UploadDiagnostics
  IPDiagnostics.UploadDiagnostics.IncrementalResult
  IPDiagnostics.UploadDiagnostics.PerConnectionResult
  IPDiagnostics.X_PRPLWARE-COM_DownloadConfig
  IPDiagnostics.X_PRPLWARE-COM_DownloadResult
  IPDiagnostics.X_PRPLWARE-COM_DownloadResult.Config
  IPDiagnostics.X_PRPLWARE-COM_DownloadResult.Process
  IPDiagnostics.X_PRPLWARE-COM_UploadConfig
  IPDiagnostics.X_PRPLWARE-COM_UploadResult
  IPDiagnostics.X_PRPLWARE-COM_UploadResult.Config
  IPDiagnostics.X_PRPLWARE-COM_UploadResult.IncrementalResult
  IPDiagnostics.X_PRPLWARE-COM_UploadResult.PerConnectionResult
  IPDiagnostics.X_PRPLWARE-COM_UploadResult.Process
  KernelFaults
  KernelFaults.KernelFault
  LEDs
  LEDs.LED
  Logical
  Logical.Interface
  Logical.X_PRPLWARE-COM_Subnet
  Logical.X_PRPLWARE-COM_Subnet.Config
  MCASTD
  MCASTD.Debug
  MCASTD.Debug.Zone
  MCASTD.Intf
  MCASTD.Tuner
  MQTT
  MQTT.Capabilities
  MQTT.Client
  MQTTBroker
  MQTTBroker.Broker
  ManagementServer
  ManagementServer.ACSTransfers
  ManagementServer.ACSTransfers.ACSTransfer
  ManagementServer.ConnRequest
  ManagementServer.HeartbeatPolicy
  ManagementServer.InformParameter
  ManagementServer.InternalSettings
  ManagementServer.ManageableDevice
  ManagementServer.Mapping
  ManagementServer.SMM
  ManagementServer.SMM.DUStateChangeComplete
  ManagementServer.State
  ManagementServer.Stats
  ManagementServer.Subscription
  ManagementServer.Transfers
  ManagementServer.Transfers.ScheduleDownload
  MultiSettings
  MultiSettings.Profile
  NAT
  NAT.InterfaceSetting
  NAT.PortMapping
  NAT.PortTrigger
  NAT.X_PRPLWARE-COM_StaticNAT
  NAT.X_PRPLWARE-COM_StaticNAT.Host
  NeighborDiscovery
  NeighborDiscovery.InterfaceSetting
  NetDev
  NetDev.ConversionTable
  NetDev.ConversionTable.Protocol
  NetDev.ConversionTable.Scope
  NetDev.ConversionTable.Table
  NetDev.Link
  NetDev.Rule
  NetDev.Stats
  NetModel
  NetModel.Intf
  Optical
  Optical.Interface
  PCP
  PCP.Client
  PPP
  PPP.Interface
  PacketInterception
  PacketInterception.CommunicationConfig
  PacketInterception.CommunicationConfig.Socket
  PacketInterception.Condition
  PacketInterception.Interception
  PacketInterception.PacketHandler
  PeriodicFileTransfer
  PeriodicFileTransfer.FileTypeConfig
  PeriodicFileTransfer.Profile
  PeriodicFileTransfer.Stats
  PeriodicFileTransfer.Transfer
  PersistentConfiguration
  PersistentConfiguration.BackupFile
  PersistentConfiguration.Config
  PersistentConfiguration.Config.Security
  PersistentConfiguration.Service
  PowerStatus
  PowerStatus.PowerSensor
  ProcessFaults
  ProcessFaults.ProcessFault
  ProcessMonitor
  ProcessMonitor.Test
  ProxyManager
  QoS
  QoS.Classification
  QoS.Node
  QoS.Queue
  QoS.QueueStats
  QoS.Scheduler
  QoS.Shaper
  Reboot
  Reboot.Reboot
  Reboot.X_PRPLWARE-COM_Reasons
  Rlyeh
  Rlyeh.Authentication
  Rlyeh.Authentication.Stats
  Rlyeh.Images
  RouterAdvertisement
  RouterAdvertisement.InterfaceSetting
  Routing
  Routing.Policy
  Routing.RIP
  Routing.RIP.InterfaceSetting
  Routing.RouteInformation
  Routing.RouteInformation.InterfaceSetting
  Routing.Router
  SFPs
  SFPs.AllowedSFPs
  SFPs.AllowedSFPs.AllowedSFP
  SFPs.Mgmt
  SFPs.Mgmt.SFF8472
  SFPs.SFPCage
  SFPs.SFPProperties
  SFPs.SFPProperties.SFP
  SSH
  SSH.AuthorizedKey
  SSH.Server
  Schedules
  Schedules.Schedule
  Security
  Security.CABundle
  Security.Certificate
  SoftwareModules
  SoftwareModules.Config
  SoftwareModules.Config.Repository
  SoftwareModules.DeploymentUnit
  SoftwareModules.ExecEnv
  SoftwareModules.ExecutionUnit
  SoftwareModules.LocalManagement
  SoftwareModules.LocalManagement.Action
  SoftwareModules.NetworkConfig
  SoftwareModules.NetworkConfig.Interfaces
  Syslog
  Syslog.Action
  Syslog.Filter
  Syslog.Source
  Syslog.Template
  System
  TemperatureStatus
  TemperatureStatus.TemperatureSensor
  Time
  Time.Client
  Time.Server
  Timingila
  Timingila.CthulhuAdapters
  Timingila.CthulhuAdapters.CthulhuCommandDefaults
  Timingila.CthulhuAdapters.CthulhuCommandDefaults.create
  Timingila.CthulhuAdapters.CthulhuCommandDefaults.remove
  Timingila.CthulhuAdapters.CthulhuCommandDefaults.update
  Timingila.CthulhuAdapters.CthulhuCommandMapping
  Timingila.CthulhuAdapters.SoftwareModulesFuncArgsOverload
  Timingila.CthulhuAdapters.SoftwareModulesTable
  Timingila.RlyehPluginsConfig
  Timingila.RlyehPluginsInfo
  Timingila.RlyehPluginsInfo.LoadedPlugins
  UPnP
  UPnP.Device
  UPnP.Device.Capabilities
  UPnP.X_PRPLWARE-COM_IGDConfig
  UPnPDescription
  UPnPDescription.DeviceDescription
  UPnPDescription.DeviceInstance
  UPnPDescription.ServiceInstance
  UPnPDiscovery
  UPnPDiscovery.Device
  UPnPDiscovery.RootDevice
  UPnPDiscovery.Service
  USB
  USB.Interface
  USB.Port
  USB.USBHosts
  USB.USBHosts.AllowedDevice
  USB.USBHosts.Host
  Unbound-br-lan
  Unbound-lo
  UserInterface
  UserInterface.HTTPAccess
  Users
  Users.Group
  Users.Role
  Users.SupportedShell
  Users.User
  WANManager
  WANManager.WAN
  WiFi
  WiFi.APMLD
  WiFi.AccessPoint
  WiFi.AutoCommitMgr
  WiFi.AutoNeighbourAddition
  WiFi.Config
  WiFi.DaemonMgt
  WiFi.DaemonMgt.Daemon
  WiFi.EndPoint
  WiFi.Radio
  WiFi.SSID
  WiFi.Vendor
  WiFi.bSTAMLD
  WiFi.wps_DefParam
  WiFiScheduler
  WiFiScheduler.Group
  WiFiScheduler.Group.Schedule
  WiFiScheduler.Network
  WiFiScheduler.Network.Schedule
  XPON
  XPON.ONU
  X_PRPLWARE-COM_Agent
  X_PRPLWARE-COM_Agent.Configuration
  X_PRPLWARE-COM_Agent.Info
  X_PRPLWARE-COM_Agent.Info.Fronthaul
  X_PRPLWARE-COM_Agent.WPS
  X_PRPLWARE-COM_Controller
  X_PRPLWARE-COM_Controller.AgentConnectedEvent
  X_PRPLWARE-COM_Controller.AgentConnectedEvent.AgentConnected
  X_PRPLWARE-COM_Controller.AgentConnectedEvent.AgentConnected.Neighbor
  X_PRPLWARE-COM_Controller.AgentConnectedEvent.AgentConnected.Radio
  X_PRPLWARE-COM_Controller.AgentConnectedEvent.AgentConnected.Radio.BSS
  X_PRPLWARE-COM_Controller.AgentConnectedEvent.AgentConnected.Radio.BSS.STA
  X_PRPLWARE-COM_Controller.AgentDisconnectedEvent
  X_PRPLWARE-COM_Controller.AgentDisconnectedEvent.AgentDisconnected
  X_PRPLWARE-COM_Controller.AgentDisconnectedEvent.AgentDisconnected.Neighbor
  X_PRPLWARE-COM_Controller.AgentDisconnectedEvent.AgentDisconnected.Radio
  X_PRPLWARE-COM_Controller.AgentDisconnectedEvent.AgentDisconnected.Radio.BSS
  X_PRPLWARE-COM_Controller.AgentDisconnectedEvent.AgentDisconnected.Radio.BSS.STA
  X_PRPLWARE-COM_Controller.Configuration
  X_PRPLWARE-COM_Controller.Configuration.QoS
  X_PRPLWARE-COM_Controller.Configuration.TrafficSeparation
  X_PRPLWARE-COM_Controller.SteerEvent
  X_PRPLWARE-COM_ProcessManager
  X_PRPLWARE-COM_ProcessManager.PWHM
  X_PRPLWARE-COM_ProcessManager.PrplMesh
  X_PRPLWARE-COM_ProcessManager.Sensing
  X_PRPLWARE-COM_WiFiController
  X_PRPLWARE-COM_WiFiController.AssociationEvent
  X_PRPLWARE-COM_WiFiController.AssociationEvent.AssociationEventData
  X_PRPLWARE-COM_WiFiController.AssociationEvent.AssociationEventData.HTCapabilities
  X_PRPLWARE-COM_WiFiController.AssociationEvent.AssociationEventData.VHTCapabilities
  X_PRPLWARE-COM_WiFiController.AssociationEvent.AssociationEventData.WiFi6Capabilities
  X_PRPLWARE-COM_WiFiController.AssociationEvent.AssociationEventData.WiFi6Capabilities.MCSNSS
  X_PRPLWARE-COM_WiFiController.DisassociationEvent
  X_PRPLWARE-COM_WiFiController.DisassociationEvent.DisassociationEventData
  X_PRPLWARE-COM_WiFiController.FailedConnectionEvent
  X_PRPLWARE-COM_WiFiController.FailedConnectionEvent.FailedConnectionEventData
  X_PRPLWARE-COM_WiFiController.Network
  X_PRPLWARE-COM_WiFiController.Network.AccessPoint
  X_PRPLWARE-COM_WiFiController.Network.AccessPoint.Security
  X_PRPLWARE-COM_WiFiController.Network.Device
  X_PRPLWARE-COM_WiFiController.Network.Device.APMLD
  X_PRPLWARE-COM_WiFiController.Network.Device.APMLD.APMLDConfig
  X_PRPLWARE-COM_WiFiController.Network.Device.APMLD.AffiliatedAP
  X_PRPLWARE-COM_WiFiController.Network.Device.APMLD.STAMLD
  X_PRPLWARE-COM_WiFiController.Network.Device.APMLD.STAMLD.AffiliatedSTA
  X_PRPLWARE-COM_WiFiController.Network.Device.APMLD.STAMLD.STAMLDConfig
  X_PRPLWARE-COM_WiFiController.Network.Device.APMLD.STAMLD.STATIDLinkMap
  X_PRPLWARE-COM_WiFiController.Network.Device.APMLD.STAMLD.WiFi7Capabilities
  X_PRPLWARE-COM_WiFiController.Network.Device.APMLD.TIDLinkMap
  X_PRPLWARE-COM_WiFiController.Network.Device.BTMSteeringDisallowedSTAList
  X_PRPLWARE-COM_WiFiController.Network.Device.CACStatus
  X_PRPLWARE-COM_WiFiController.Network.Device.CACStatus.CACActiveChannel
  X_PRPLWARE-COM_WiFiController.Network.Device.CACStatus.CACAvailableChannel
  X_PRPLWARE-COM_WiFiController.Network.Device.CACStatus.CACNonOccupancyChannel
  X_PRPLWARE-COM_WiFiController.Network.Device.Default8021Q
  X_PRPLWARE-COM_WiFiController.Network.Device.IEEE1905Security
  X_PRPLWARE-COM_WiFiController.Network.Device.Interface
  X_PRPLWARE-COM_WiFiController.Network.Device.Interface.Neighbor
  X_PRPLWARE-COM_WiFiController.Network.Device.Interface.Stats
  X_PRPLWARE-COM_WiFiController.Network.Device.LocalSteeringDisallowedSTA
  X_PRPLWARE-COM_WiFiController.Network.Device.MultiAPCapabilities
  X_PRPLWARE-COM_WiFiController.Network.Device.MultiAPDevice
  X_PRPLWARE-COM_WiFiController.Network.Device.MultiAPDevice.Backhaul
  X_PRPLWARE-COM_WiFiController.Network.Device.MultiAPDevice.Backhaul.CurrentOperatingClassProfile
  X_PRPLWARE-COM_WiFiController.Network.Device.MultiAPDevice.Backhaul.Stats
  X_PRPLWARE-COM_WiFiController.Network.Device.Radio
  X_PRPLWARE-COM_WiFiController.Network.Device.Radio.BSS
  X_PRPLWARE-COM_WiFiController.Network.Device.Radio.BSS.MultiAPSteering
  X_PRPLWARE-COM_WiFiController.Network.Device.Radio.BSS.QMDescriptor
  X_PRPLWARE-COM_WiFiController.Network.Device.Radio.BSS.STA
  X_PRPLWARE-COM_WiFiController.Network.Device.Radio.BSS.STA.HTCapabilities
  X_PRPLWARE-COM_WiFiController.Network.Device.Radio.BSS.STA.MeasurementReport
  X_PRPLWARE-COM_WiFiController.Network.Device.Radio.BSS.STA.MultiAPSTA
  X_PRPLWARE-COM_WiFiController.Network.Device.Radio.BSS.STA.MultiAPSTA.SteeringHistory
  X_PRPLWARE-COM_WiFiController.Network.Device.Radio.BSS.STA.MultiAPSTA.SteeringSummaryStats
  X_PRPLWARE-COM_WiFiController.Network.Device.Radio.BSS.STA.TIDQueueSizes
  X_PRPLWARE-COM_WiFiController.Network.Device.Radio.BSS.STA.VHTCapabilities
  X_PRPLWARE-COM_WiFiController.Network.Device.Radio.BSS.STA.WiFi6Capabilities
  X_PRPLWARE-COM_WiFiController.Network.Device.Radio.BSS.STA.WiFi6Capabilities.MCSNSS
  X_PRPLWARE-COM_WiFiController.Network.Device.Radio.BSS.SetQoSManagementInput
  X_PRPLWARE-COM_WiFiController.Network.Device.Radio.BackhaulSta
  X_PRPLWARE-COM_WiFiController.Network.Device.Radio.CACCapability
  X_PRPLWARE-COM_WiFiController.Network.Device.Radio.CACCapability.CACMethod
  X_PRPLWARE-COM_WiFiController.Network.Device.Radio.CACCapability.CACMethod.OpClassChannels
  X_PRPLWARE-COM_WiFiController.Network.Device.Radio.CACCapability.CACMethod.OpClassChannels.Channel
  X_PRPLWARE-COM_WiFiController.Network.Device.Radio.Capabilities
  X_PRPLWARE-COM_WiFiController.Network.Device.Radio.Capabilities.AKMBackhaul
  X_PRPLWARE-COM_WiFiController.Network.Device.Radio.Capabilities.AKMFrontHaul
  X_PRPLWARE-COM_WiFiController.Network.Device.Radio.Capabilities.HTCapabilities
  X_PRPLWARE-COM_WiFiController.Network.Device.Radio.Capabilities.OperatingClasses
  X_PRPLWARE-COM_WiFiController.Network.Device.Radio.Capabilities.OperatingClasses.NonOperable
  X_PRPLWARE-COM_WiFiController.Network.Device.Radio.Capabilities.VBSSCapabilities
  X_PRPLWARE-COM_WiFiController.Network.Device.Radio.Capabilities.VHTCapabilities
  X_PRPLWARE-COM_WiFiController.Network.Device.Radio.Capabilities.WiFi6APRole
  X_PRPLWARE-COM_WiFiController.Network.Device.Radio.Capabilities.WiFi6APRole.MCSNSS
  X_PRPLWARE-COM_WiFiController.Network.Device.Radio.Capabilities.WiFi6Capabilities
  X_PRPLWARE-COM_WiFiController.Network.Device.Radio.Capabilities.WiFi6Capabilities.MCSNSS
  X_PRPLWARE-COM_WiFiController.Network.Device.Radio.Capabilities.WiFi6bSTARole
  X_PRPLWARE-COM_WiFiController.Network.Device.Radio.Capabilities.WiFi6bSTARole.MCSNSS
  X_PRPLWARE-COM_WiFiController.Network.Device.Radio.Capabilities.WiFi7APRole
  X_PRPLWARE-COM_WiFiController.Network.Device.Radio.Capabilities.WiFi7APRole.EMLMRFreqSeparation
  X_PRPLWARE-COM_WiFiController.Network.Device.Radio.Capabilities.WiFi7APRole.EMLSRFreqSeparation
  X_PRPLWARE-COM_WiFiController.Network.Device.Radio.Capabilities.WiFi7APRole.NSTRFreqSeparation
  X_PRPLWARE-COM_WiFiController.Network.Device.Radio.Capabilities.WiFi7APRole.STRFreqSeparation
  X_PRPLWARE-COM_WiFiController.Network.Device.Radio.Capabilities.WiFi7bSTARole
  X_PRPLWARE-COM_WiFiController.Network.Device.Radio.Capabilities.WiFi7bSTARole.EMLMRFreqSeparation
  X_PRPLWARE-COM_WiFiController.Network.Device.Radio.Capabilities.WiFi7bSTARole.EMLSRFreqSeparation
  X_PRPLWARE-COM_WiFiController.Network.Device.Radio.Capabilities.WiFi7bSTARole.NSTRFreqSeparation
  X_PRPLWARE-COM_WiFiController.Network.Device.Radio.Capabilities.WiFi7bSTARole.STRFreqSeparation
  X_PRPLWARE-COM_WiFiController.Network.Device.Radio.CurrentOperatingClassProfile
  X_PRPLWARE-COM_WiFiController.Network.Device.Radio.ScanCapability
  X_PRPLWARE-COM_WiFiController.Network.Device.Radio.ScanCapability.OpClassChannels
  X_PRPLWARE-COM_WiFiController.Network.Device.Radio.ScanCapability.OpClassChannels.Channel
  X_PRPLWARE-COM_WiFiController.Network.Device.Radio.ScanResult
  X_PRPLWARE-COM_WiFiController.Network.Device.Radio.ScanResult.OpClassScan
  X_PRPLWARE-COM_WiFiController.Network.Device.Radio.ScanResult.OpClassScan.ChannelScan
  X_PRPLWARE-COM_WiFiController.Network.Device.Radio.ScanResult.OpClassScan.ChannelScan.NeighborBSS
  X_PRPLWARE-COM_WiFiController.Network.Device.Radio.SpatialReuse
  X_PRPLWARE-COM_WiFiController.Network.Device.Radio.UnassociatedSTA
  X_PRPLWARE-COM_WiFiController.Network.Device.Radio.X_PRPLWARE-COM_CACCompletion
  X_PRPLWARE-COM_WiFiController.Network.Device.Radio.X_PRPLWARE-COM_CACCompletion.Pairs
  X_PRPLWARE-COM_WiFiController.Network.Device.SPRule
  X_PRPLWARE-COM_WiFiController.Network.Device.SSIDtoVIDMapping
  X_PRPLWARE-COM_WiFiController.Network.Device.bSTAMLD
  X_PRPLWARE-COM_WiFiController.Network.Device.bSTAMLD.bSTAMLDConfig
  X_PRPLWARE-COM_WiFiController.Network.MultiAPSteeringSummaryStats
  X_PRPLWARE-COM_WiFiController.Network.X_PRPLWARE-COM_Group
  X_PRPLWARE-COM_WiFiMapped
  X_PRPLWARE-COM_WiFiMapped.WiFi
  X_PRPLWARE-COM_WiFiMapped.WiFi.DataElements
  X_PRPLWARE-COM_WiFiMapped.WiFi.DataElements.X_PRPLWARE-COM_Controller
  X_PRPLWARE-COM_WiFiMapped.WiFi.X_PRPLWARE-COM_ProcessManager
  X_PRPLWARE-COM_WiFiMapped.WiFi.X_PRPLWARE-COM_WiFiSensing
  X_PRPLWARE-COM_WiFiSensing
  X_PRPLWARE-COM_WiFiSensing.Session
  X_PRPLWARE-COM_WiFiSensing.Session.Exchange
